config/routes.rb
Community::Application.routes.draw do
  get 'dashboard' => "meals#signup", as: :dashboard
  get 'my_groups' => "groups#my_groups", as: :my_groups
  get 'welcome' => "welcome#index", as: :welcome
  get 'group/attempt/:id' => "groups#attempt_to_join_group", as: :attempt_join_group
  post 'group/attempt/:id' => "groups#join_group", as: :attempt_join_group_post
  post 'welcome/check_group' => "welcome#check_group", as: :check_group
  get 'welcome/check_group' => "welcome#check_group"
  devise_for :diners, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => "signup"}, 
      controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords" }

  resources :ingredients
  resources :meals

  resources :groups

  post 'change_current_group/:id' => "groups#change_current_group", as: :change_current_group

  
  post 'meals/pay' => "meals#pay", as: :pay
  post 'meals/signup_post' => 'meals#signup_post', as: :signup_meal
  post 'meals/get_attendence' => 'meals#get_attendance', as: :get_attendence_meal

  post 'venmo/pay' => 'venmo#pay', as: :pay_with_venmo
  get 'venmo_oauth' => 'venmo#oauth', as: :venmo_oauth
  get 'venmo/unlink' => 'venmo#unlink', as: :venmo_unlink
  get 'venmo/link' => 'venmo#link', as: :venmo_link
  get 'venmo/signup' => 'venmo#signup', as: :signup_with_venmo

  resources :diners

  root 'meals#signup'

end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id            :integer          not null, primary key
#  admin_id      :integer
#  password_hash :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  name          :string(255)
#

require 'bcrypt'
class Group < ActiveRecord::Base
  include BCrypt

  validates :password_hash, :admin_id, :name, presence: true

  validates_uniqueness_of :name

  has_and_belongs_to_many :diners

  belongs_to :admin, class_name: "Diner", foreign_key: "admin_id"

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    return if new_password.blank? # don't set a blank password
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :change_current_group, :attempt_to_join_group, :join_group]
  before_filter :verify_yourself_or_admin!, only: [:edit, :update, :destroy]

  skip_before_filter :check_group!

  def verify_yourself_or_admin!
    @group.admin.id == current_diner.id || authenticate_admin!
  end

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.where.not(id: current_diner.groups).includes(:admin)
  end

  def my_groups
    @groups = current_diner.groups.includes(:admin)
    @only_my_groups = true
    render :index
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @diners = @group.diners
  end

  # GET /groups/new
  def new
    @group_name = session[:group_name]
    session[:group_name] = nil # served its purpose, clear it.
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new
    @group.name = params[:group][:name]
    if params[:password][:password] != params[:password_confirmation][:password_confirmation]
      @group.errors.add(:base, 'Passwords do not match!')
      return render action: 'new'
    end

    @group.password = params[:password][:password]
    @group.admin = current_diner
    @group.diner_ids = params[:group][:diner_ids] << current_diner.id


    respond_to do |format|
      if @group.save
        current_diner.update_attribute(:current_group_id, @group.id)
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    if @group.password != params[:current_password][:current_password]
      @group.errors.add(:base, "Current password was incorrect")
      return render action: 'edit'
    end
    if params[:password][:password] != params[:password_confirmation][:password_confirmation]
      @group.errors.add(:base, 'Passwords do not match!')
      return render action: 'edit'
    end
    @group.diner_ids = params[:group][:diner_ids] << current_diner.id
    respond_to do |format|
      if @group.update(name: params[:group][:name], password: params[:password][:password])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to my_groups_url }
      format.json { head :no_content }
    end
  end

  def change_current_group
    unless current_diner.groups.include? @group
      return redirect_to my_groups_path, error: "You don't appear to be in #{@group.name}"
    end
    current_diner.update_attribute(:current_group_id, @group.id)
    redirect_to my_groups_path, notice: "Successfully switched to #{@group.name}"
  end

  def attempt_to_join_group
  end

  def join_group
    if @group.password != params[:password]
      return redirect_to attempt_join_group_path(@group), alert: "Oops that password was incorrect"
    end

    @group.diners << current_diner
    current_diner.update_attribute(:current_group_id, @group.id)
    redirect_to my_groups_path, notice: "Successfully joined group #{@group.name}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @group.errors.any? %>
    <div class = "alert alert-danger" role="alert">
      <div><b>Error(s)</b></div>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
      <% end %> 
    </div> 
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :value => (@group_name || @group.name) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= password_field :password, :password %>
      <% if @group.id %><i>(leave blank if you don't want to change it)</i><% end %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password_confirmation, :class => 'control-label' %>
    <div class="controls">
      <%= password_field :password_confirmation, :password_confirmation %>
    </div>
  </div>

  <% if @group.id %>
    <div class="control-group">
      <%= f.label :current_password, :class => 'control-label' %>
      <div class="controls">
        <%= password_field :current_password, :current_password %>
        <i>(we need your current password to confirm your changes)</i>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :diners_to_be_in_group, :class => 'control-label' %>
    <div class="controls">
      <%= 
        f.collection_select :diner_ids, Diner.where.not(id: current_diner), :id, :name, {}, {:"data-placeholder"=>"Add your friends", :class=>"chosen chosen-select chosen-select-no-results chosen-select-no-single chosen-select-deselect", multiple: true}
      %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

<script>//for autocomplete search for diners
  var config = {
    '.chosen'                  : {},
    '.chosen-select'           : {},
    '.chosen-select-deselect'  : {allow_single_deselect:true},
    '.chosen-select-no-single' : {disable_search_threshold:10},
    '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'}
  }
  for (var selector in config) {
    $(selector).chosen(config[selector]);
  }
</script>

app/views/groups/attempt_to_join_group.html.erb
<div class="page-header">
  <h1>Joining Group <%= link_to @group.name, @group %></h1>
  <h2>Group admin is: <%= link_to @group.admin, @group.admin %>
</div>

<%= form_for attempt_join_group_post_path(@group), :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= password_field_tag :password %>
    </div>
  </div>

  <%= f.submit 'Join Group', :class => 'btn btn-primary join-group' %>
<% end %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn'  %>
</div>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%= @only_my_groups ? 'Your' : 'Other' %> Groups</h1>
</div>
<table class="table table-striped" id="datatable">
  <thead>
    <tr>
      <th>Status</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:admin) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <% if current_diner.current_group_id == group.id %>
          <td><%= link_to 'Current Group', diners_path %></td>
        <% elsif @only_my_groups %>
          <td><%= button_to 'Join Group', change_current_group_path(group), :class => 'btn btn-mini btn-primary' %></td>
        <% else %>
          <td><%= link_to 'Join?', attempt_join_group_path(group), :class => 'btn btn-mini btn-primary' %></td>
        <% end %>

        <td><%= link_to group.name, group %></td>
        <td><%= group.admin %></td>
        <td><%= group.created_at %></td>
        <td>
        <% if verify_yourself_or_admin(group.admin.id) %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_group_path(group), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        group_path(group),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

<% if @only_my_groups %>
  <%= link_to 'Find Other Groups',
              groups_path,
              :class => 'btn btn-primary' %>
<% else %>
  <%= link_to 'Switch Group View',
              my_groups_path,
              :class => 'btn btn-primary' %>
<% end %>

<script>
  var oTable = $('#datatable').dataTable({sPaginationType: "full_numbers"});

  oTable.fnSort( [1,'asc'] ); // sort by name
</script>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %>:<small> <%=@group.name %></smalL></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Admin:</strong></dt>
  <dd><%= @group.admin %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @group.name %></dd>
  <dt>Diners:</dt>
  <% @diners.each do |diner| %>
    <dd><%= diner %></dd>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn'  %>
  <% if verify_yourself_or_admin(@group.admin_id) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_group_path(@group), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                group_path(@group),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>