config/routes.rb
Community::Application.routes.draw do
  get 'dashboard' => "meals#signup", as: :dashboard
  get 'my_groups' => "groups#my_groups", as: :my_groups
  get 'welcome' => "welcome#index", as: :welcome
  get 'group/attempt/:id' => "groups#attempt_to_join_group", as: :attempt_join_group
  post 'group/attempt/:id' => "groups#join_group", as: :attempt_join_group_post
  post 'welcome/check_group' => "welcome#check_group", as: :check_group
  get 'welcome/check_group' => "welcome#check_group"
  devise_for :diners, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => "signup"}, 
      controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords" }

  resources :ingredients
  resources :meals

  resources :groups

  post 'change_current_group/:id' => "groups#change_current_group", as: :change_current_group

  
  post 'meals/pay' => "meals#pay", as: :pay
  post 'meals/signup_post' => 'meals#signup_post', as: :signup_meal
  post 'meals/get_attendence' => 'meals#get_attendance', as: :get_attendence_meal

  post 'venmo/pay' => 'venmo#pay', as: :pay_with_venmo
  get 'venmo_oauth' => 'venmo#oauth', as: :venmo_oauth
  get 'venmo/unlink' => 'venmo#unlink', as: :venmo_unlink
  get 'venmo/link' => 'venmo#link', as: :venmo_link
  get 'venmo/signup' => 'venmo#signup', as: :signup_with_venmo

  resources :diners

  root 'meals#signup'

end

app/models/diner.rb
# == Schema Information
#
# Table name: diners
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  role                   :string(255)
#  current_group_id       :integer
#  venmo_token            :string(255)
#  venmo_refresh_token    :string(255)
#

class Diner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_and_belongs_to_many :meals
  has_and_belongs_to_many :groups
  has_many :ingredients, :dependent => :destroy

  belongs_to :current_group, class_name: "Group", foreign_key: "current_group_id"
  validates_presence_of :name

  before_validation :set_default_name

  def set_default_name
    update_attribute(:name, email) if name.empty?
  end
	
  def cost
    meals.sum { |meal| meal.cost_for_single_diner }
  end

  #calculates how much another diner owes you
  def request_amount_from(another_diner_id, group_id) 
    total_payment = 0.0
    ingredients.where(finished: true, group_id: group_id).each do |ingredient|
      total_payment += ingredient.payment_owed_by(another_diner_id)
    end

    total_payment
  end

  #calculates how much you owe another diner
  def get_amount_owed(another_diner_id, group_id)
    another_diner = Diner.find(another_diner_id)
    another_diner.request_amount_from(id, group_id)
  end

  #calculates balance between two diners: finds balance by looking at all finished ingredients, then adjusts by calculating payments
  #if positive, another_diner owes the current diner
  def balance_between(another_diner_id, group_id)
    total_requested = request_amount_from(another_diner_id, group_id) - get_amount_owed(another_diner_id, group_id)
    total_paid = 0.0
    #another_diner pays current diner
    Payment.where(to_id: id, from_id: another_diner_id, group_id: group_id).each do |payment|
      total_paid += payment.amount
    end
    #current_diner pays another_diner
    Payment.where(from_id: id, to_id: another_diner_id, group_id: group_id).each do |payment|
      total_paid -= payment.amount
    end
    total_requested-total_paid
  end

  def to_s
    name
  end

  def soft_destroy
    update_attributes(venmo_token: nil, venmo_refresh_token: nil, name: "DELETED")
  end

end

app/controllers/diners_controller.rb
class DinersController < ApplicationController
  before_action :set_diner, only: [:show, :edit, :update, :destroy]
  before_filter :verify_yourself_or_admin!, only: [:edit, :update, :destroy]

  # GET /diners
  # GET /diners.json
  def index
    @diners = Diner.where(id: current_group_ids)
  end

  # GET /diners/1
  # GET /diners/1.json
  def show
    @payments = Payment.where(group: current_group).
                        where('(from_id = ? AND to_id = ?) OR (from_id = ? AND to_id = ?)', current_diner.id, @diner.id, @diner.id, current_diner.id).
                        order(:created_at).
                        includes(:from, :to)
  end

  # GET /diners/1/edit
  def edit
  end

  # PATCH/PUT /diners/1
  # PATCH/PUT /diners/1.json
  def update
    respond_to do |format|
      if @diner.update(diner_params)
        format.html { redirect_to @diner, notice: 'Diner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @diner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diners/1
  # DELETE /diners/1.json
  def destroy
    #add admin check here!
    @diner.destroy
    respond_to do |format|
      format.html { redirect_to diners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diner
      @diner = Diner.where(id: current_group_ids).find_by_id(params[:id])
      return if @diner
      diner = Diner.find_by_id(params[:id])
      redirect_to root_path, alert: "You must currently be in #{diner.name}'s group to access information about him" if diner
      redirect_to root_path, alert: "Couldn't find that diner!"
    end

    def verify_yourself_or_admin!
      # can only modify other diners if you are global admin
      @diner.id == current_diner.id || authenticate_admin!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diner_params
      params.require(:diner).permit(:name)
    end
end

app/helpers/diners_helper.rb
module DinersHelper
end

app/views/diners/_form.html.erb
<%= form_for @diner, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                diners_path, :class => 'btn' %>
  </div>
<% end %>

app/views/diners/edit.html.erb
<%- model_class = Diner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diners/index.html.erb
<%- model_class = Diner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped" id="datatable">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @diners.each do |diner| %>
      <tr>
        <td><%= link_to diner.name, diner %></td>
        <td><%= diner.email %></td>
        <td>
          <% if current_diner.id == diner.id %>
            <%= link_to 'Edit Profile', edit_diner_registration_path, :class => 'btn btn-mini' %>
          <% end %>
          <% if is_admin? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_diner_path(diner), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        diner_path(diner),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  var oTable = $('#datatable').dataTable({sPaginationType: "full_numbers"});
</script>

app/views/diners/new.html.erb
<%- model_class = Diner -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diners/show.html.erb
<%- model_class = Diner -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @diner.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @diner.email %></dd>
  <dt>Balance:</dt>
  <dd>
    <% if @diner != current_diner %>
      <% balance = @diner.balance_between(current_diner.id, current_group.id) %>
      <% if balance != 0 %>
        <span class="<%= balance < 0 ? 'green' : 'red'%>"><%= number_to_currency balance.abs %></span>
      <% else %>
        <%= number_to_currency 0 %>
      <% end %>
    <% else %>
      <%= number_to_currency 0 %>
    <% end %>
  </dd>
  <div class="col-md-6">
    <h3>Meals <%= @diner.name %> is involved in</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Chef</th>
          <th>Cost of Meal</th>
          <th>Cost for Single Diner</th>
        </tr>
      </thead>
      <tbody>
        <% @diner.meals.where(group: current_group).includes(:chef).each do |meal| %>
          <tr>
            <td><%= link_to meal.name, meal %></td>
            <td><%= link_to meal.chef, meal.chef %></td>
            <% if meal.all_ingredients_finished? %>
              <td><%= number_to_currency meal.cost %></td>
              <td><%= number_to_currency meal.cost_for_single_diner %></td>
            <% else %>
              <td>Some ingredients are not finished</td>
              <td>Some ingredients are not finished</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if current_diner != @diner %>
    <div class="col-md-6">
      <h3>Your Payment History with <%= @diner.name %></h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <% @payments.each do |p| %>
            <tr>
              <td><%= p.created_at %></td>
              <td>
                <%= link_to p.from, p.from %> paid <%= link_to p.to, p.to %>
                <%= number_to_currency p.amount %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              diners_path, :class => 'btn'  %>
  <% if verify_yourself_or_admin(@diner.id) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_diner_path(@diner), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                diner_path(@diner),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>