config/routes.rb
Community::Application.routes.draw do
  get 'dashboard' => "meals#signup", as: :dashboard
  get 'my_groups' => "groups#my_groups", as: :my_groups
  get 'welcome' => "welcome#index", as: :welcome
  get 'group/attempt/:id' => "groups#attempt_to_join_group", as: :attempt_join_group
  post 'group/attempt/:id' => "groups#join_group", as: :attempt_join_group_post
  post 'welcome/check_group' => "welcome#check_group", as: :check_group
  get 'welcome/check_group' => "welcome#check_group"
  devise_for :diners, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => "signup"}, 
      controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords" }

  resources :ingredients
  resources :meals

  resources :groups

  post 'change_current_group/:id' => "groups#change_current_group", as: :change_current_group

  
  post 'meals/pay' => "meals#pay", as: :pay
  post 'meals/signup_post' => 'meals#signup_post', as: :signup_meal
  post 'meals/get_attendence' => 'meals#get_attendance', as: :get_attendence_meal

  post 'venmo/pay' => 'venmo#pay', as: :pay_with_venmo
  get 'venmo_oauth' => 'venmo#oauth', as: :venmo_oauth
  get 'venmo/unlink' => 'venmo#unlink', as: :venmo_unlink
  get 'venmo/link' => 'venmo#link', as: :venmo_link
  get 'venmo/signup' => 'venmo#signup', as: :signup_with_venmo

  resources :diners

  root 'meals#signup'

end

app/models/meal.rb
# == Schema Information
#
# Table name: meals
#
#  id         :integer          not null, primary key
#  date       :date
#  created_at :datetime
#  updated_at :datetime
#  owner_id   :integer
#  name       :string(255)
#  chef_id    :integer
#  group_id   :integer
#

class Meal < ActiveRecord::Base
  belongs_to :owner, class_name: "Diner", foreign_key: "owner_id"
  belongs_to :chef, class_name: "Diner", foreign_key: "chef_id"
  belongs_to :group
  has_and_belongs_to_many :ingredients
  has_and_belongs_to_many :diners

  validates_presence_of :name, :owner, :chef, :date
  validate :has_diners?
  validate :has_ingredients?

  validate :check_group_id_of_ingredients

  accepts_nested_attributes_for :ingredients, :diners

  before_destroy :sanity_check_finished_ingredients

  after_save :update_ingredient_servings

  def update_ingredient_servings
    # just update all the ingredients servings since likely changed after save
    ingredients.each do |i|
      i.update_servings
    end
  end

  def new_ingredient_ids=(ids)
    # we need to collect all the dropped ingredient ids so that we can update their servings
    dropped_ids = ingredient_ids - ids

    # execute the join table modify so that update_servings will work properly
    original_ingredient_ids(ids) # this is the original def of ingredient_ids=
    dropped_ids.each do |id|
      i = Ingredient.find(id)
      i.update_servings
    end
  end

  # alias method chain to handle attribute=
  alias_method :original_ingredient_ids, :ingredient_ids=
  alias_method :ingredient_ids=, :new_ingredient_ids=


  def check_group_id_of_ingredients
    # TODO
    # this if statement should really be done at database level if possible
    if (ingredients.reject { |ing| ing.group_id == group_id }).any?
      errors.add(:base, "Group ID doesn't line up!")
      # nuke the relation
      ingredients.clear
    end
  end

  def has_diners?
    errors.add(:diner_ids, "A meal must have at least one diner") if !self.diners.any?
  end

  def has_ingredients?
    errors.add(:ingredient_ids, "A meal must have at least one ingredient") if !self.ingredients.any?
  end

  def cost
    ingredients.to_a.sum{|ing| ing.cost_for_number_of_diners(diners.count) }
  end

  def cost_for_single_diner
    all_ingredients_finished? ? ingredients.sum{|ing| ing.cost_for_number_of_diners(1) } : 0
  end

  def all_ingredients_finished?
    !ingredients.where(finished: false).any?
  end

  def sanity_check_finished_ingredients
    ingredients.each do |i|
      if i.meals.count == 1
        # ensure that no ingredient can be finished without being in any meals.
        i.update_attribute(:finished, false)
      end
    end
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy]
  before_filter :verify_yourself_or_admin!, only: [:edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    index_setup
    @meal = Meal.new
    @ingredient = Ingredient.new
  end

  def index_setup
    @defaultDinerID = current_diner.id
    @meals = Meal.where(group: current_group).includes(:chef, :owner, :ingredients)
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @diners = @meal.diners
    @ingredients = @meal.ingredients
  end

  # GET /meals/new
  def new
    @meal = Meal.new
    @meal.date = Date.today
    @defaultDinerID = current_diner.id
  end

  # GET /meals/1/edit
  def edit
    @edit = true
    @defaultDinerID = @meal.owner.id
    @ingredient = Ingredient.new
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = Meal.new(meal_params)
    @meal.owner = current_diner #owner should always be the guy that's logged in
    @meal.group = current_group

    respond_to do |format|
      if @meal.save
        update_ingredients_after_save
        flash[:notice] = 'Meal was successfully created.'
        format.js { render action: 'meal_success', status: :created, location: @meal }
      else
        format.js { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  def signup
    signup_setup
    @meal = Meal.new
    @ingredient = Ingredient.new
  end

  def signup_setup
    @meals = Meal.where(group: current_group)
    @valid_dates = @meals.pluck(:date) # array of dates
    
    @balances = []
    Diner.where(id: current_group_ids).where.not(id: current_diner.id).each do |d|
      @balances << {diner_name: d.name, diner_id: d.id, balance: current_diner.balance_between(d.id, current_group.id), venmo_token: d.venmo_token}
    end

    @payments = Payment.where(group: current_group).where('from_id = ? OR to_id = ?', current_diner.id, current_diner.id).order(:created_at).includes(:from, :to)
  end

  def signup_post
    date = Date.strptime(params['date'],"%m/%d/%Y")
    meals_saw = Meal.where(date: date, group: current_group).pluck(:id)
    meals_checked = params['meal_ids'] || [] # or nothing checked
    current_meals = current_diner.meal_ids
    meals_unchecked = meals_saw - meals_checked
    meals_to_remove = meals_unchecked & current_meals

    current_diner.meal_ids = (current_meals | meals_checked) - meals_to_remove
    current_diner.save

    redirect_to root_path, notice: "Successfully saved attendence for #{date.to_date}"
  end
  
  # POST 
  def pay
    @payment = Payment.new(pay_params)
    @payment.from_id = current_diner.id
    @payment.group = current_group
    unless current_group_ids.include? @payment.to_id
      return redirect_to, alert: "Can't make payments across groups!"
    end
    if @payment.save
      redirect_to root_path, notice: "Payment made."
    else
      redirect_to root_path, alert: @payment.errors.full_messages
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        update_ingredients_after_save
        flash[:notice] = 'Meal was successfully updated.'
        format.js { render action: 'meal_updated_success', status: :updated, location: @meal }
      else
        format.js { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end

  def generate_html(meal)
    "
    <div>
      <input id='meal_diners_ids_#{meal.id}' name='meal_ids[]' type='checkbox' #{meal.diners.include?(current_diner) ? 'checked=checked' : ''} value='#{meal.id}'>
      <b>Join</b>
      <br>
      <b>Name:</b> #{meal.name}
      <br>
      <b>Chef:</b> #{meal.chef}
      <br>
      <b>Current Diners:</b> #{meal.diners.pluck(:name).join(', ')}
      <br>
      <b>Ingredients in Meal:</b> #{meal.ingredients.pluck(:name).join(', ')}
    </div>
    "
  end

  #for the join meal modal form to retrieve the attendance record for each meal id
  def get_attendance
    #build a boolean attendance record that hashes to each meal date
    date = Date.strptime(params['date'],"%m/%d/%Y")
    meals = Meal.where(date: date, group: current_group).includes(:diners, :chef)
    meals_html = []
    meals.each do |meal|
      meals_html << generate_html(meal)
    end
    html_string = meals_html.join('')
    render :text => html_string
  end

  def update_ingredients_after_save
    ingredients_saw_ids = Ingredient.where(group: current_group, finished: false).pluck(:id)
    if @meal
      ingredients_saw_ids |= @meal.ingredients.pluck(:id)
    end

    params[:finished_ingredient_ids].delete("") # purge empty string if chosen creates
    params[:finished_ingredient_ids].map!(&:to_i) # easier to work with all ints

    #check off the finished ingredients
    finished_ids = params[:finished_ingredient_ids] & params[:meal][:ingredient_ids]
    finished_ids.each do |id|
      i = Ingredient.find_by_id(id)
      if i && i.group == current_group
        i.finished = true
        i.save
      end
    end

    #uncheck unfinished ingredients
    unfinished_ids = ingredients_saw_ids - finished_ids
    unfinished_ids.each do |id|
      i = Ingredient.find_by_id(id)
      if i && i.group == current_group
        i.finished = false
        i.save
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.where(group: current_group).find(params[:id])
    end

    def verify_yourself_or_admin!
      # you can modify meals if you are the owner, chef, admin of the group, or global admin
      @meal.owner == current_diner || @meal.chef == current_diner || @meal.group.admin == current_diner || authenticate_admin!
    end

    def pay_params
      params.permit(:amount, :to_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_params
      setup_ingredients_attributes
      setup_date
      params.require(:meal).permit(:name, :chef_id, :date, :group_id, :diner_ids => [], :ingredient_ids => [])
    end

    # ingredient_attributes needs to be an array of hashes
    def setup_ingredients_attributes
      params[:meal][:ingredient_ids] = [] unless params[:meal][:ingredient_ids] # set ids to empty if no ingredients selected
      params[:meal][:ingredient_ids].delete("") # purge empty string if chosen creates
      params[:meal][:ingredient_ids].map!(&:to_i) # easier to work with all ints
    end

    def setup_date
      return if params[:meal][:date].is_a? Date
      return if params[:meal][:date].empty?
      params[:meal][:date] = Date.strptime(params[:meal][:date],"%m/%d/%Y")
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_diner_fields.html.erb
<div class="control-group">
  <%= f.label :name, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :name, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :email, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :email, :class => 'text_field' %>
  </div>
</div>

<%= f.check_box :_destroy %>
<%= f.label :_destroy, "Remove Diner" %>

app/views/meals/_form.js.erb
$(document).bind('ajaxError', 'form#actual-meal-form', function(event, jqxhr, settings, exception){
  // note: jqxhr.responseJSON undefined, parsing responseText instead

  // TODO this is sort of hacky, but distinguish between the external meal form and internal
  // ingredient form failing
  if (settings.url == "/ingredients.json") {
    $('#actual-ingredient-form').render_form_errors( $.parseJSON(jqxhr.responseText) );
  } else {
    $(event.data).render_form_errors( $.parseJSON(jqxhr.responseText) );
  }

});

$('#ingredient-form-insert').on('click', function () {
  var text = $('#ingredient-form').is(":visible") ? "Add new ingredient" : "Close ingredient form";
  $(this).text(text);
  $('#ingredient-form').slideToggle();
});

$("#meal-form").on("shown.bs.modal", function() {
  var config = {
    '.chosen'                  : {},
    '.chosen-select'           : {},
    '.chosen-select-deselect'  : {allow_single_deselect:true},
    '.chosen-select-no-single' : {disable_search_threshold:10},
    '.chosen-select-no-results': {no_results_text:'Oops, nothing found!'}
  }

  for (var selector in config) {
    $(".chosen").chosen(config[selector]);
  }

  $('#meal_ingredient_ids').on('change', function(e, params) {
    var selected = params.selected;
    var $target = $('#_finished_ingredient_ids');
    if (selected) {
      var option = $('#meal_ingredient_ids option[value=' + selected + ']').clone();
      var opt = option[0];
      $target.append(opt);
      $target.find(opt).removeAttr("selected");
      $target.trigger("chosen:updated");

      return;
    }

    var deselected = params.deselected;
    if (deselected) {
      var option = $('#_finished_ingredient_ids option[value=' + deselected + ']');
      option.remove();
      $target.trigger("chosen:updated");
    }
  });

  $('.chosen').on('chosen:showing_dropdown', function (evt, params) {
    var absolute_position = $(this).closest('.modal-body').scrollTop() + $(this).closest('.form-group').position().top;
    $('.modal-body').animate({
      scrollTop: absolute_position - 150 // scroll to the middle of the chosen clicked
    }, 1000);
  });
});

$('#actual-ingredient-form').submit(function (e) {
  $.ajax({
    url: "<%= ingredients_path(format: 'json') %>",
    type: 'POST',
    data: $(this).serialize()
  }).done(function (data) {
    $('#meal_ingredient_ids').append('<option selected="true" value=' + data.id + '>' + data.name + '</option>');
    $('#meal_ingredient_ids').trigger("chosen:updated");
    $('#meal_ingredient_ids').trigger('change', { 'selected': data.id });
    $('#actual-ingredient-form').ajax_form_success();
  });
  e.preventDefault();
  return false;
});

$(document).ready(function(){
  $('#ingredient-form').insertAfter('#ingredient-form-insert');

  $("#datepicker").datepicker();
  <% if @meal.date %>
    var rubydate = "<%= @meal.date.strftime('%Y-%m-%d') %>"
    var parts = rubydate.split("-");
    var dt = new Date(parseInt(parts[0], 10), // year
                parseInt(parts[1], 10) - 1, // month
                parseInt(parts[2], 10)); // day
    $("#datepicker").datepicker("setDate", dt );
  <% end %>

});

app/views/meals/_join_meal.html.erb
<div class="modal fade" id="join-meal-form" aria-hidden="true" style="display:none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Join a Meal</h4>
      </div>
      <div class="modal-body">
        <%= form_tag signup_meal_path, :class => "form" do %>
          <h3>Signup for <span id="signup-date-display"></span></h3>
          <%= hidden_field_tag(:date, :nil, id: 'signup-date-param') %>
          <div id='fill-in-form-join'></div>

            <div class="modal-footer">
              <%= submit_tag nil, :class => 'btn btn-primary' %>
              <button type="button" class="btn" data-dismiss="modal">Cancel</button>
            </div>

        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/meals/_signup.js.erb
$(document).ready(function(){
  var MEAL_CLASS = "meal";
  //EVENT BINDINGS  
  $(".calendar").click(function(event){

    var $target = $(event.target);
    $(".alert-block").fadeIn();
    var clicked_class = $target.attr('class');
    if (!clicked_class) {
      return; // likely clicked on day (e.g. Mon) header.  Block the event.
    }
    if ($target.attr('class').indexOf(MEAL_CLASS) > -1){
      //selected a meal
      //make an ajax call to find out who signed up on that date
      $('#signup-date-display').html($target.attr('data-date'));
      $('#signup-date-param').val($target.attr('data-date'));
      $("#join-meal-form").modal();
      $("#meal-form").css("z-index","100");
      $("#join-meal-form").css("z-index","9999");

      $.ajax({
        type: "POST",
        dataType: "html",
        url: '<%= get_attendence_meal_path %>',
        data: { "date": $target.attr('data-date')},
        success: function(data){
          $('#fill-in-form-join').html(data);
        },
        error: function(){
          alert("Cannot sign up for meal!");
        }
      });

    } else {
      var date_attr = $target.attr('data-date');
      if (!date_attr) {
        return; // user likely clicked on month header.  Block the event.
      }

      $("#meal-form").css("z-index","9999");
      $("#meal-submit").attr('name', 'signup');
      $("#join-meal-form").css("z-index","100");
      $("#meal-form").modal();

      var parts = date_attr.split("/");
      var dt = new Date(parseInt(parts[2], 10), // year
                  parseInt(parts[0], 10) - 1, // month
                  parseInt(parts[1], 10)); // day
      $("#datepicker").datepicker("setDate", dt );

    }
  });
});

app/views/meals/edit.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

<script>
  // turbolinks don't use document on ready
  $(document).ready(function () {
    $("#meal-form").modal('show');
  });
  $("#meal-form").on('hidden', function () {
    window.location.href = '<%= meals_path %>';
  })
</script>

app/views/meals/index.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped" id="datatable">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:chef) %></th>
      <th>All Ingredients Finished?</th>
      <th>Cost</th>
      <th><%= model_class.human_attribute_name(:date) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= link_to meal.name, meal_path(meal) %></td>
        <td><%= link_to meal.chef, meal.chef %></td>
        <td><%= meal.all_ingredients_finished? %></td>
        <td><%= meal.all_ingredients_finished? ? number_to_currency(meal.cost) : 'Some ingredients are not finished' %></td>
        <td><%= meal.date.to_date %></td>
        <td>
          <% if verify_yourself_or_group_admin(meal.owner.id) || verify_yourself_or_group_admin(meal.chef.id) %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_meal_path(meal), :class => 'btn btn-mini edit-btn' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        meal_path(meal),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_meal_path,
            :class => 'btn btn-primary', :id=>"new-meal-btn" %>
<%= render :partial => "form" %>

<script>
  $("#new-meal-btn").click(function(event){
    event.preventDefault();
    $("#meal-form").modal('show');
  });

  var oTable = $('#datatable').dataTable({sPaginationType: "full_numbers"});

  oTable.fnSort( [4,'desc'] ); // show most recent at top
</script>

app/views/meals/meal_updated_success.js.erb
window.location = "<%= meals_path %>";

app/views/meals/new.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meals/show.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1>Meal Summary</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:chef) %>:</strong></dt>
  <dd><%= link_to @meal.chef, @meal.chef %></dd>
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @meal.date.to_date.to_s %></dd>
  <dt>Cost</dt>
  <dd><%= @meal.all_ingredients_finished? ? number_to_currency(@meal.cost) : 'Some ingredients are not finished' %></dd>
  <dt>Diners:</dt>
  <% @diners.each do |diner| %>
    <dd><%= link_to diner, diner %></dd>
  <% end %>
  <h2>Ingredients in this Meal</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Finished</th>
        <th>Total Servings</th>
        <th>Total Cost of Ingredient</th>
        <th>Cost towards this meal</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td><%= link_to ingredient, ingredient %></td>
          <td><%= ingredient.finished ? 'yes' : 'no' %></td>
          <td><%= ingredient.servings %></td>
          <td><%= number_to_currency(ingredient.cost) %></td>
          <td><%= ingredient.finished ? number_to_currency(ingredient.cost_for_number_of_diners(@diners.count)) : 'Ingredient not finished' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              meals_path, :class => 'btn'  %>
  <% if verify_yourself_or_admin(@meal.owner.id) || verify_yourself_or_admin(@meal.chef.id) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_meal_path(@meal), :class => 'btn' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                meal_path(@meal),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/meals/signup.html.erb
<div class="page-header">
  <h1>Dashboard</h1>

</div>
<div class="container">
  <div class="row">
    <div class = "col-md-4">
    <h3>Meal Summary</h3>
    <p> Highlighted days represent days that have meals. </p>
    <%=
      calendar(:year => Date.today.year, :month => Date.today.month) do |day|
        if @valid_dates.include?(day)
          [day.mday, {:class => "meal" }]
        else 
          [day.mday, {} ]
        end
      end 
    %>

    </div>

    <div class="col-md-4">
      <h3>Balance Summary</h3>
      <div class="legend">
        <div class="green">Amount expected</div>
        <div class="red">Amount owed</div>
      </div>
      <table id="balances">
        <thead>
          <tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% balanceCount = 0 %>
          <% @balances.each do |balance| %>
            <% if balance[:balance] > 0 %>
              <tr>
                <td><%= link_to balance[:diner_name], diner_path(balance[:diner_id]) %></td>
                <td colspan="2"><span class="green"><%= number_to_currency balance[:balance] %></span></td>
              </tr>
              <% balanceCount+=1 %>
            <% elsif balance[:balance] < 0 %>
              <% balanceCount+=1 %>
              <tr>
                <td><%= link_to balance[:diner_name], diner_path(balance[:diner_id]) %></td>
                <td><span class="red"><%= number_to_currency -balance[:balance] %></span></td>
                <td>
                  <div class="btn-group">
                    <% amount = -balance[:balance] #we have to negate the balance they're paying if they're in debt %>
                    <% if balance[:venmo_token] %>
                      <%= link_to ("<small>Pay w/</small>"+image_tag('venmo-white.png')).html_safe, pay_with_venmo_path(to_diner_id: balance[:diner_id]), :method =>"post", :class => "btn btn-sm btn-venmo" %>
                      
                      <button type="button" class="btn btn-sm btn-venmo dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu">
                        <li><%= button_to "Pay w/ cash", pay_path(to_id: balance[:diner_id], amount: amount), :class => "btn btn-sm btn-primary", :id=>"btn-cash", :method =>"post" %></li>
                        <li id="payment-form-wrapper">
                          <%= form_tag pay_path, :id=>"payment-form" do %>
                          <%= number_field_tag :amount, nil, :min => 0, :id=>"pay-amount-tooltip",:class=>"form-control", :data => {:placement=>"bottom", :toggle=>"tooltip"}, :title=>"Specify a particular amount to pay", step: 0.01 %>
                          <%= hidden_field_tag :to_id, nil, :value => balance[:diner_id] %>
                          <%= submit_tag "Pay", :class => 'btn btn-sm btn-primary' %>
                        <% end %>
                        </li>
                      </ul>
                    <% else %>
                      <%= link_to "Pay", pay_path(to_id: balance[:diner_id], amount: amount), :class => "btn btn-md btn-primary", :method =>"post" %>
                      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu">
                        <li id="payment-form-wrapper">
                          <%= form_tag pay_path, :id=>"payment-form" do %>
                          <%= number_field_tag :amount, nil, :min => 0, :id=>"pay-amount-tooltip",:class=>"form-control", :data => {:placement=>"right", :toggle=>"tooltip"}, :title=>"Specify a particular amount to pay", step: 0.01 %>
                          <%= hidden_field_tag :to_id, nil, :value => balance[:diner_id] %>
                          <%= submit_tag "Pay", :class => 'btn btn-sm btn-primary' %>
                        <% end %>
                        </li>
                        <li> <button type="button" class="btn btn-link venmo-tooltip" data-toggle="tooltip" data-placement="right" <% if current_diner.venmo_token  %> title="Ask <%=balance[:diner_name]%> to setup venmo!" <% else %> title="Edit your profile to link Venmo" <% end %> >Pay w/ venmo</button></li>
                      </ul>

                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          <% end %>
          <% if balanceCount==0%>
            <tr>
              <td colspan="3">
               <div class="alert alert-info" role="alert">
               <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                You have no balance history with any members of your group. 
              </br>Create new meals or signup for existing meals with the calendar.
              </div>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-4">
      <h3>Payment History</h3>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
          <% @payments.each do |p| %>
            <tr>
              <td><%= p.created_at %></td>
              <td>
                <%= link_to p.from, p.from %> paid <%= link_to p.to, p.to %>
                <%= number_to_currency p.amount %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div> <!-- end row -->

  <!-- forms -->
  <%= render :partial => "join_meal" %>
  <%= render "form" %>
</div>
<% content_for :javascript do %>
  <script type="text/javascript">
    $("#payment-form").click(function(e){
      $("#pay-amount-tooltip").tooltip("show");
      e.stopPropagation();
    });
    <%= render :partial => "signup.js", :formats => [:js] %>
    $(".dropdown-menu").click(function(e){
      e.stopPropagation();//stops the dropdown menu from dissapearing
    });
    $(".venmo-tooltip").tooltip()
  </script>
<% end %>