config/routes.rb
Community::Application.routes.draw do
  get 'dashboard' => "meals#signup", as: :dashboard
  get 'my_groups' => "groups#my_groups", as: :my_groups
  get 'welcome' => "welcome#index", as: :welcome
  get 'group/attempt/:id' => "groups#attempt_to_join_group", as: :attempt_join_group
  post 'group/attempt/:id' => "groups#join_group", as: :attempt_join_group_post
  post 'welcome/check_group' => "welcome#check_group", as: :check_group
  get 'welcome/check_group' => "welcome#check_group"
  devise_for :diners, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => "signup"}, 
      controllers: { registrations: "registrations", sessions: "sessions", passwords: "passwords" }

  resources :ingredients
  resources :meals

  resources :groups

  post 'change_current_group/:id' => "groups#change_current_group", as: :change_current_group

  
  post 'meals/pay' => "meals#pay", as: :pay
  post 'meals/signup_post' => 'meals#signup_post', as: :signup_meal
  post 'meals/get_attendence' => 'meals#get_attendance', as: :get_attendence_meal

  post 'venmo/pay' => 'venmo#pay', as: :pay_with_venmo
  get 'venmo_oauth' => 'venmo#oauth', as: :venmo_oauth
  get 'venmo/unlink' => 'venmo#unlink', as: :venmo_unlink
  get 'venmo/link' => 'venmo#link', as: :venmo_link
  get 'venmo/signup' => 'venmo#signup', as: :signup_with_venmo

  resources :diners

  root 'meals#signup'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community</title>
  <%= stylesheet_link_tag "application", "http://fonts.googleapis.com/css?family=Open+Sans", "http://fonts.googleapis.com/css?family=Ubuntu:300,400,700", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= favicon_link_tag '/favicon.ico' %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%if current_diner %>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav" id="nav">
            <li><%=link_to image_tag("logo.png", :id=>"logo-image"), dashboard_path, :class=>"navbar-brand brand" %></li>
            <li><%=link_to "Meals", meals_path %></li>
            <li><%=link_to "Diners", diners_path %></li>
            <li><%=link_to "Ingredients", ingredients_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <%= render 'devise/menu/login_items' %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <% if current_diner %><div class="flash-push"> <% end %>
    <%= bootstrap_flash %>
  <% if current_diner %></div><%end%>

  <% if current_diner %><div class="container"><% end %>
    <%= yield %>
  <% if current_diner %></div><% end %>

<div class="flash-push"></div>
<%= yield :javascript %>
</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Community</title>
  <%= stylesheet_link_tag    "application" ,"welcome", "animate", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "http://fonts.googleapis.com/css?family=Ubuntu:400,700", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>
<body>
<%= bootstrap_flash %>
<%= yield %>

</body>
</html>